[book]
title = "Notes"
authors = ["Antonio Gelameris"]
language = "en"
src = "src"

[preprocessor.links]
renderers = ["html"]
some_extra_feature = true

[output.html]
site-url = "https://notes.toniogela.dev/"
git-repository-url = "https://github.com/TonioGela/mdbook"
additional-css = ["custom.css"]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
no-section-label = true
input-404 = "404.md"

[output.html.search]
enable = true
limit-results = 35
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
